In [83]:
%autosave 60
import numpy as np
import pandas as pd

Autosaving every 60 seconds


# Q1
## P-center greedy heuristics 

#### Dijkstra Algorithm to find distances between every pair of nodes
https://github.com/xsank/cabbird/blob/master/graph/dijkstra.py

In [29]:
from collections import defaultdict

def dijkstra(g,start,end):
    if start==end:
        return 0
    if not (start in g and end in g):
        raise Exception('invalid node %s or %s' % (start,end))
    labels={}
    path=defaultdict(list)
    for vertex in g:
        labels[vertex]=0 if vertex==start else float("inf")
    drops=labels.copy()
    while drops:
        min_v=min(drops,key=drops.get)
        path[min_v].append(min_v)
        for i in g[min_v]:
            if labels[i]>(labels[min_v]+g[min_v][i]):
                drops[i]=labels[i]=labels[min_v]+g[min_v][i]
                path[i]=[]
                path[i].extend(path[min_v])
        del drops[min_v]
#     result=[]
#     result.append(path[end])
#     result.append(labels[end])
    return labels[end]

def get_vertices(g):
    temp=[]
    for item in g:
        temp.append(item)
    return temp

if __name__=="__main__":
    
    G = {
    'a':{'b':7,'c':4,'d':5},
    'b':{'a':7,'e':5},
    'c':{'a':4,'d':7,'f':3},
    'd':{'a':5,'c':7,'f':5,'g':9},
    'e':{'b':5,'g':6},
    'f':{'c':3,'d':5,'g':8},
    'g':{'d':9,'e':6,'f':8}
}
    
    
#     dijkstra(G,'a','f')

    Vertices = get_vertices(G)
    
    Distance_Matrix = {}
    for i in Vertices:
        Distance_Matrix [i] = {}

    for i in Vertices:
        for j in Vertices:
            Distance_Matrix [i][j] = dijkstra(G,i,j)

    print(Distance_Matrix)
#     print(Distance_Matrix['a']['f'])


{'a': {'a': 0, 'g': 14, 'd': 5, 'c': 4, 'f': 7, 'e': 12, 'b': 7}, 'g': {'a': 14, 'g': 0, 'd': 9, 'c': 11, 'f': 8, 'e': 6, 'b': 11}, 'd': {'a': 5, 'g': 9, 'd': 0, 'c': 7, 'f': 5, 'e': 15, 'b': 12}, 'c': {'a': 4, 'g': 11, 'd': 7, 'c': 0, 'f': 3, 'e': 16, 'b': 11}, 'f': {'a': 7, 'g': 8, 'd': 5, 'c': 3, 'f': 0, 'e': 14, 'b': 14}, 'e': {'a': 12, 'g': 6, 'd': 15, 'c': 16, 'f': 14, 'e': 0, 'b': 5}, 'b': {'a': 7, 'g': 11, 'd': 12, 'c': 11, 'f': 14, 'e': 5, 'b': 0}}


#### Greedy Heuristics 

In [51]:
s=[]

# random choose one node: here we choose the first node in Vertices
s.append(Vertices[0])


# first iteration
temp = 0
for j in Vertices:
    if j not in s:
        if Distance_Matrix [s[0]][j] > temp:
            temp = Distance_Matrix [s[0]][j] 
            firstIter = j
s.append(firstIter)  
            
# later iteration
temp = 0
for j in Vertices:
    if j not in s:
        temp2= 9^999
        for i in s:
#             print(i,j,Distance_Matrix [i][j])
            if Distance_Matrix [i][j] < temp2:
                temp2 = Distance_Matrix [i][j] 
#         print(j,"-",temp2)
        if temp2 > temp:
            temp = temp2
            nextIter = j
            
# iteration until
s.append(nextIter)        

print(s)

['a', 'g', 'f']


#### Solution:
#### Since we only need to allocate 2 facilities among 7 demand nodes, we could stop when two nodes have been chosen. The facilities should be located at A and G

# Q3
## Clarke & Wright’s savings algorithm

Implement the Clarke & Wright’s savings algorithm for the setting we discussed in class. Specifically, we have n demand locations: i = 1, . . . , n, and a location 0 which is the base of our fleet. There is no constraint on the number of vehicles. Each vehicle has a capacity constraint C. You would use the savings algorithm to find a set of routes to cover all demand locations, where each route starts and ends at location 0, and no demand locations appear in more than 1 route.  

Your algorithm should return a list of routes, as well as the total demand of each route. For example, in class we ran the savings algorithm manually on an example set of 7 demand nodes and obtained a solution with 4 routes: 0−4−0, 0−5−0, 0−2−3−0, 0−1−7−6−0, each with total demand 16, 15, 18 and 18. For this example your algorithm should return two lists: [[5], [4], [2,3], [1,7,6]], [16, 15, 18, 18], note the order of the two lists must match, i.e., the first entry of the second list must be the demand of the first entry of the first list, and so forth.


#### Implementation of Clark Wright

In [ ]:
def savings_clarke_wright(demand, distance, capacity):
      """
      demand: @list[float], the demand of each location. If there are N demand
               locations, this list will be an 1*(N+1) list, where demand[i] is
               the demand for location i, for i=1, ..., N. demand[0] is always 0.
      distance: @list[list[float]], the distance between each pair of locations.
               If there are N demand locations(and 0 is the base), this 2-d list
               will have size (N+1)*(N+1), where distance[i][j] is the distance
               between location i and location j. You may assume distance[i][i]
               is 0 for all i and distance[i][j] = distance[j][i] for all i,j.
      capacity: @float, the capacity constraint for each vehicle.
      return
        routes:@list[list[int]], list of routes computed by the algorithm.
        order:@list[float], list of total demand corresponding to each route.
      """
    
    
    result=[]
    result.append(routes)
    result.append(order)
    return result

#### Data input
Capacity constraint is 25 units.

In [72]:
C = 25
# We could here input as integer rather than float.

The distance matrix is as follows.

In [76]:
df = pd.read_clipboard(header=None) 
distanceMatrix = df.as_matrix()
distanceMatrix

array([[ 0.  ,  6.23,  4.48,  2.83,  4.  ,  5.  ,  2.  ,  5.45],
       [ 6.23,  0.  ,  5.66,  6.16,  8.  ,  8.24,  7.47,  9.16],
       [ 4.48,  5.66,  0.  ,  2.83,  5.66,  8.06,  6.  ,  3.62],
       [ 2.83,  6.16,  2.83,  0.  ,  2.83,  5.39,  7.47,  7.07],
       [ 4.  ,  8.  ,  5.66,  2.83,  0.  ,  3.  ,  7.47,  2.62],
       [ 5.  ,  8.24,  8.06,  5.39,  3.  ,  0.  ,  7.47,  3.5 ],
       [ 2.  ,  7.47,  6.  ,  7.47,  7.47,  7.47,  0.  ,  2.16],
       [ 5.45,  9.16,  3.62,  7.07,  2.62,  3.5 ,  2.16,  0.  ]])

Demand of each node is as follows. Node 0 is deport with 0 demand.

In [77]:
df = pd.read_clipboard(header=None) 
demandMatrix = df.as_matrix()
demandMatrix = demandMatrix.T
demandlist = demandMatrix[0] # array([[ 75,...,25]])
demandlist
# We could here input as integer rather than float.

array([ 0, 10, 12,  6, 13, 14,  7, 10])

#### Model solving

In [ ]:
if __name__=="__main__":
    print(savings_clarke_wright(demandlist, distanceMatrix, C))

[ 0 10 12  6 13 14  7 10]


25

In [89]:
demand = demandlist
distance = distanceMatrix
capacity = C

# use double ended que (deque) to represent route
from collections import deque

# Only the starting or ending node on a route can be merged
# Use a dict (python implements it by hashmap) to store the starting and ending node on a route to improve efficiency
route = {}
for i in range(1,len(distanceMatrix)):
    route[i] = deque('%s' %i) #'0' and '-' is set be added later
# print(route)


savings=[]

def deque_capacity(d):
    temp=0
    for item in d:
         temp+=demandlist[item]
    return temp
 
    
    
m=deque('12')
print(m)
print(deque_capacity(m))




deque(['1', '2'])
22


/Users/Jessie/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:21: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
